#!/usr/bin/env bash

# POST /repos/:owner/:repo/commits/:sha/comments

set -ex

: "${GITHUB_TOKEN?}"
: "${GITHUB_REPOSITORY?}"
: "${GITHUB_EVENT_PATH?}"

URI=https://api.github.com
API_VERSION=3
API_HEADER="Accept: application/vnd.github.${API_VERSION}+json"
AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"

q() {
  jq --raw-output "$1" "$GITHUB_EVENT_PATH"
}

main() {
  local body full_name sha
  body='{"body": "High five!"}'
  full_name=$(q .repository.full_name)
  sha=$(q .after)
  if [[ ! "$sha" ]]; then
    sha=$(q .head)
  fi
  echo "High fiving the push"
  curl -sSL -H "$AUTH_HEADER" -H "$API_HEADER" \
    --data "$body" \
    "$URI/repos/$full_name/commits/$sha/comments"
}

main "$@"
