#!/usr/bin/env bash

set -ex

: "${GITHUB_TOKEN?}"
: "${GITHUB_REPOSITORY?}"
: "${GITHUB_EVENT_PATH?}"

URI=https://api.github.com
API_VERSION=3
API_HEADER="Accept: application/vnd.github.${API_VERSION}+json"
AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"

main() {
  local action merged owner repo body number
  body='{"body": "High five!"}'
  action=$(jq -r .action "$GITHUB_EVENT_PATH")
  merged=$(jq --raw-output .pull_request.merged "$GITHUB_EVENT_PATH")
  echo "DEBUG -> action: $action merged: $merged"
  [[ "$action" = closed ]] || return 0
  [[ "$merged" = true ]] || return 0
  number=$(jq --raw-output .pull_request.head.number "$GITHUB_EVENT_PATH")
  owner=$(jq --raw-output .pull_request.head.repo.owner.login "$GITHUB_EVENT_PATH")
  repo=$(jq --raw-output .pull_request.head.repo.name "$GITHUB_EVENT_PATH")
  echo "High fiving the pr"
  curl -sSL -H "$AUTH_HEADER" -H "$API_HEADER" "$URI/repos/$owner/$repo/issues/$number/comments" --data "$body"
}

main "$@"
