name: wip-to-draft

on:
  pull_request

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: Run
        run: |
          API_HEADER="Accept: application/vnd.github.v3+json; application/vnd.github.antiope-preview+json"
          AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"

          action=$(jq --raw-output .action "$GITHUB_EVENT_PATH")
          number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          title=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH")

          printf 'title "%s" ' "$title"
          if [[ $title =~ \W[Ww][Ii][Pp]\W ]]; then
            echo 'contains WIP'
          else
            echo 'does not contain WIP'
          fi
